### ISSUE TITLE
Choosing Schema Registry Subject Name Strategy

### ISSUE THREAD

**Issue by enamrik** [mostafa/xk6-kafka#85] opened 2022-06-10 21:36 UTC
## Problem:

There are different naming strategies out there for naming the subject of a schema as seen [here](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#subject-name-strategy). 

The schema registry implementation in this library hardcodes the TopicNameStrategy strategy as seen below.

https://github.com/mostafa/xk6-kafka/blob/8cceb22900446181eb0d5468354dbe2cd837e53e/avro.go#L23

In my current project, we use a different strategy RecordNameStrategy. This is because we have topics that can contain messages of different schemas. 

## Request:

Can we consider allowing the user to pass a method that builds the subject name? This way the user can implement which ever naming strategy they use.

**Comment by mostafa** [comment] 2022-06-11 08:30
Hey @enamrik,

thanks for pointing it out. I am thinking about [exporting](https://github.com/mostafa/xk6-kafka/issues/55) the whole functionality to JS. Please upvote the issue. I'd also be happy to see and review contributions.

There are other issues you might be interested:
- https://github.com/mostafa/xk6-kafka/issues/54
- https://github.com/mostafa/xk6-kafka/issues/53
- https://github.com/mostafa/xk6-kafka/issues/50

**Comment by enamrik** [comment] 2022-06-14 19:32
Hi @mostafa, I gave it shot and tried adding support for subject name strategies: https://github.com/mostafa/xk6-kafka/pull/88. I tried to keep the change footprint small but I do have some suggested refactorings if you're interested. Please let me know what you think. 

I'm also exploring another need I have which is for the consumer to support the special offsets i.e. -1 = latest, -2 = earliest. I have the changes and test on a branch https://github.com/enamrik/xk6-kafka/blob/handle_special_offsets/consumer.go#L40. Wanted to get your thoughts on this first PR before attempting a PR on special offsets.

**Comment by mostafa** [comment] 2022-06-14 21:40
@enamrik Awesome! Thanks for your contribution. 🙏
I'll try to review the PR as soon as I can and possibly merge it. Also, I'd be very happy to know more about your refactoring suggestions. Please check the tickets for known issues.

**Comment by enamrik** [comment] 2022-06-14 22:40
> @enamrik Awesome! Thanks for your contribution. 🙏 I'll try to review the PR as soon as I can and possibly merge it. Also, I'd be very happy to know more about your refactoring suggestions. Please check the tickets for known issues.

Yes, now that I've added the features I needed for work and I'm more familiar with the codebase, I'd love to help on issues. I'll take a look at those you mentioned.

**Comment by mostafa** [comment] 2022-06-16 16:18
Thanks to @enamrik, the issue is addressed in #88.

@enamrik Feel free to re-open the issue if you have anything else to add.

**Closed by mostafa** 2022-06-16 16:18 UTC
Labels: enhancement

**Comment by mostafa** [comment] 2022-06-20 10:53
Released in [v0.11.0](https://github.com/mostafa/xk6-kafka/releases/tag/v0.11.0).
