### ISSUE TITLE
Usage of deprecated k6 APIs

### ISSUE THREAD

**Issue by thmshmm** [mostafa/xk6-kafka#38] opened 2022-04-19 19:43 UTC
When running the latest xk6-kafka from master the following message appears:
`Module 'k6/x/kafka' is using deprecated APIs that will be removed in k6 v0.38.0, for more details on how to update it see https://k6.io/docs/extensions/guides/create-an-extension/#advanced-javascript-extension`

What should be done:
- Identify deprecated API calls
- Replace API calls

https://k6.io/docs/extensions/guides/create-an-extension/#advanced-javascript-extension

**Comment by mostafa** [comment] 2022-05-02 16:04
@thmshmm I fixed the issue in #41. but the are some regressions, which I'll fix.

**Comment by mostafa** [comment] 2022-05-04 17:40
The fixes on merged now, but not released because I couldn't figure out how to test SASL (no SSL), and I need someone to test it against a working instance of Kafka with SASL PLAIN/SCRAM enabled. I'll merge this, but won't release it until I fully test it. This means that you can test the feature by compiling with the latest commits on the main branch, but it won't be available as binary and a Docker image yet.

**Closed by mostafa** 2022-05-04 17:40 UTC
