### ISSUE TITLE
How can one read the last x messages from a topic with a reader?

### ISSUE THREAD

**Issue by Bogdan405** [mostafa/xk6-kafka#213] opened 2023-04-28 13:37 UTC

**Comment by Bogdan405** [comment] 2023-04-28 14:03
Thank you, can I set the offset to the latest message somehow? Or is there a way to get the current offset without consuming all the messages?

**Comment by mostafa** [comment] 2023-04-28 14:07
@Bogdan405 
There is currently no explicit way to do it, unless you read a single message (`limit=1`).

**Comment by Bogdan405** [comment] 2023-04-28 14:10
Ok, I will keep experimenting

**Comment by mostafa** [comment] 2023-04-28 15:25
I'll close this issue, and feel free to re-open it if the issue is not resolved.

**Closed by mostafa** 2023-04-28 15:25 UTC

**Comment by Manuel-Moya** [comment] 2024-05-20 14:53
@Bogdan405 , how did you solve your requirement? I am trying to get the last message as well.
