### ISSUE TITLE
Request to add authentication through oauth bearer token

### ISSUE THREAD

**Issue by AndyKCS** [mostafa/xk6-kafka#300] opened 2024-07-25 08:50 UTC
We have xk6 setup for performance testing Kafka using TLS certs. However we are currently implementing authentication to kafka using oauth bearer tokens. If I understand correctly, I don't believe authentication with bearer tokens is currently available in xk6. Is it possible to have this added or is it still not supported in the Kafka go library?

**Comment by mostafa** [comment] 2024-07-26 09:32
Duplicate of #228.

**Closed by mostafa** 2024-07-26 09:32 UTC

**Comment by AndyKCS** [comment] 2024-07-26 12:48
Thanks for getting back to me.  I thought the go library may have been updated so wanted to check if this was in the pipeline to be looked at.
